### ISSUE TITLE
Android app installation fails if sanitized name ends up being used

### ISSUE THREAD

**Issue by vjrantal** [manifoldjs/manifoldjs-lib#6]
If an app is generated from an IP address (for example, in a development environment), the Cordova name sanitizer ends up stripping all dots and numbers and the name to be used is coming from a line like:

```
sanitizedName = 'MyManifoldJSApp';
```

The installation of an APK like this fails to error `INSTALL_PARSE_FAILED_MANIFEST_MALFORMED`, because Android doesn't allow package names to start with capital letters.

**Comment by boyofgreen** [comment]
Hi @vjrantal , can you change the pull request to be in branch v0.1.2, I'll do a proper release for this.  out of curiosity what URL are you using that triggers that, generally we only fall back to that name when all the characters are sanitized out.  Thanks for you help as always

**Comment by vjrantal** [comment]
@boyofgreen: Branch switch done.

The URL I used was something like `http://192.168.0.199:8000`. Overall, I consider this an edge case and probably not many would run into this, but thought it might be worth fixing anyways.

In some CD/CI environment, there might be cases where one wants to package an app that points to some development version of a hosted Web app that is only accessible via an IP address.

**Comment by boyofgreen** [comment]
Ahh, this makes sense as it has to filter out numbers, but I can see where this would often be used in development.  I'll take the pull request in and move it into master.
